version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

  app:
    build: .
    container_name: go_app
    command: ["./app"]
    environment:
      DATABASE_URL: "user:password@tcp(db:3306)/mydatabase?charset=utf8mb4&parseTime=True&loc=Local"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
